package simulator.observers;

import peersim.core.Network;
import simulator.model.Blockchain;

/**
 * Observer that tracks the structure of the blockchain generated by the protocol.
 */
public final class BlockchainObserver extends BaseObserver {

	public BlockchainObserver(String name) {
		super(name);
	}

	@Override
	double getValue(int index, int pid) {
		final BlockchainMetric protocol = (BlockchainMetric) Network.get(index).getProtocol(pid);
		final Blockchain blockchain = protocol.blockchain();
		return blockchain.forks();
	}

}
