package simulator.observers;

import peersim.core.Network;

/**
 * Observer that tracks the number of forks generated by the protocol.
 */
public final class ForksObserver extends BaseObserver {

	public ForksObserver(String name) {
		super(name);
	}

	@Override
	double getValue(int index, int pid) {
		final ForksMetric protocol = (ForksMetric) Network.get(index).getProtocol(pid);
		return protocol.forks(index);
	}
}
